# Generated by Django 5.1 on 2025-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isp_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
