# Generated by Django 5.1 on 2025-02-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_location_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_area', models.CharField(blank=True, max_length=255, null=True)),
                ('road_number', models.CharField(blank=True, max_length=50, null=True)),
                ('building_no', models.CharField(blank=True, max_length=50, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('router_model', models.CharField(blank=True, max_length=100, null=True)),
                ('devices', models.CharField(blank=True, choices=[('tv', 'TV'), ('mobile', 'Mobile'), ('computer', 'Computer'), ('cctv', 'CCTV'), ('others', 'Others')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('isp_username', models.CharField(max_length=100)),
                ('package_password', models.CharField(max_length=255)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_slip', models.FileField(blank=True, null=True, upload_to='packages/slips/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
