# Generated by Django 5.1 on 2025-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_additionaluserinfo_userpackageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tv', 'TV'), ('mobile', 'Mobile'), ('computer', 'Computer'), ('cctv', 'CCTV'), ('others', 'Others')], max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='building_no',
            new_name='building_name',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='isp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='devices',
        ),
        migrations.AlterField(
            model_name='userpackageinfo',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpackageinfo',
            name='isp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='devices',
            field=models.ManyToManyField(blank=True, to='accounts.device'),
        ),
    ]
