# Generated by Django 5.1 on 2025-02-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackageinfo',
            name='package_number',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
