# Generated by Django 5.1 on 2025-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userpackageinfo_package_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackageinfo',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpackageinfo',
            name='package_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='userpackageinfo',
            name='package_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
