# Generated by Django 5.1 on 2025-01-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0002_alter_complain_attachment_alter_reply_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ComplainAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complains/complain_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complains.complain')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complains/reply_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complains.reply')),
            ],
        ),
    ]
